import type { QuizQuestionT } from '@/features/quiz/model/schema';

export const DATA_TEST: QuizQuestionT[] = [
   {
      id: 9013,
      question:
         'Which directive controls whether PHP accepts session IDs from GET/POST requests?',
      description: 'Understanding session ID transmission security.',
      answers: {
         answer_a: 'session.use_only_cookies',
         answer_b: 'session.use_trans_sid',
         answer_c: 'session.auto_start',
         answer_d: 'session.secure_mode',
         answer_e: null,
         answer_f: null,
      },
      multiple_correct_answers: 'false',
      correct_answers: {
         answer_a_correct: 'false',
         answer_b_correct: 'true',
         answer_c_correct: 'false',
         answer_d_correct: 'false',
         answer_e_correct: 'false',
         answer_f_correct: 'false',
      },
      explanation:
         'The `session.use_trans_sid` directive controls whether PHP accepts session IDs passed via GET or POST requests.',
      tip: null,
      tags: [{ name: 'PHP' }],
      category: 'Code',
      difficulty: 'Hard',
   },
   {
      id: 3542,
      question:
         'Which command is used to change the I/O scheduler for a specific block device in Ubuntu?',
      description:
         'Changing the I/O scheduler can help optimize disk performance for specific workloads.',
      answers: {
         answer_a: "Use 'echo cfq | sudo tee /sys/block/sdX/queue/scheduler'",
         answer_b: "Run 'set-io-scheduler'",
         answer_c: "Type 'change-io-policy'",
         answer_d: "Use 'disk-scheduler config'",
         answer_e: null,
         answer_f: null,
      },
      multiple_correct_answers: 'false',
      correct_answers: {
         answer_a_correct: 'true',
         answer_b_correct: 'false',
         answer_c_correct: 'false',
         answer_d_correct: 'false',
         answer_e_correct: 'false',
         answer_f_correct: 'false',
      },
      explanation:
         "To change the I/O scheduler, modify the appropriate file in '/sys/block/'.",
      tip: null,
      tags: [{ name: 'Ubuntu' }],
      category: 'Docker',
      difficulty: 'Hard',
   },
   {
      id: 3125,
      question: 'How do you display the IP address of your Ubuntu machine?',
      description:
         'Knowing your IP address is useful for network configuration and troubleshooting.',
      answers: {
         answer_a: "Use 'ip addr show'",
         answer_b: "Run 'showip'",
         answer_c: "Type 'ifconfig-ip'",
         answer_d: "Use 'netinfo'",
         answer_e: null,
         answer_f: null,
      },
      multiple_correct_answers: 'false',
      correct_answers: {
         answer_a_correct: 'true',
         answer_b_correct: 'false',
         answer_c_correct: 'false',
         answer_d_correct: 'false',
         answer_e_correct: 'false',
         answer_f_correct: 'false',
      },
      explanation:
         "To display the IP address of your Ubuntu machine, use the 'ip addr show' command.",
      tip: null,
      tags: [{ name: 'Ubuntu' }],
      category: 'Linux',
      difficulty: 'Easy',
   },
   {
      id: 3353,
      question: 'How do you display disk partition information in Ubuntu?',
      description:
         'Displaying partition information helps in managing disk usage and configurations.',
      answers: {
         answer_a: "Use 'lsblk'",
         answer_b: "Run 'diskinfo'",
         answer_c: "Type 'partinfo'",
         answer_d: "Use 'showdisks'",
         answer_e: null,
         answer_f: null,
      },
      multiple_correct_answers: 'false',
      correct_answers: {
         answer_a_correct: 'true',
         answer_b_correct: 'false',
         answer_c_correct: 'false',
         answer_d_correct: 'false',
         answer_e_correct: 'false',
         answer_f_correct: 'false',
      },
      explanation: "To display disk partition information, use 'lsblk'.",
      tip: null,
      tags: [{ name: 'Ubuntu' }],
      category: 'Linux',
      difficulty: 'Medium',
   },
   {
      id: 937,
      question: 'What is a deployment in Kubernetes?',
      description: null,
      answers: {
         answer_a:
            'Deployments represent a set of multiple, identical Pods with no unique identities',
         answer_b:
            'Deployments represent a set of multiple, identical Nodes with no unique identities',
         answer_c: null,
         answer_d: null,
         answer_e: null,
         answer_f: null,
      },
      multiple_correct_answers: 'false',
      correct_answers: {
         answer_a_correct: 'true',
         answer_b_correct: 'false',
         answer_c_correct: 'false',
         answer_d_correct: 'false',
         answer_e_correct: 'false',
         answer_f_correct: 'false',
      },
      explanation: null,
      tip: null,
      tags: [{ name: 'Kubernetes' }],
      category: 'DevOps',
      difficulty: 'Medium',
   },
   {
      id: 9336,
      question:
         'Which function should be used to send JSON data securely via cURL with a `POST` request?',
      description: 'Understanding how to send JSON data using cURL in PHP.',
      answers: {
         answer_a: 'curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data))',
         answer_b: 'curl_json_post($ch, $data)',
         answer_c: 'json_post_request($ch, $data)',
         answer_d: 'curl_json_send($ch, $data)',
         answer_e: null,
         answer_f: null,
      },
      multiple_correct_answers: 'false',
      correct_answers: {
         answer_a_correct: 'true',
         answer_b_correct: 'false',
         answer_c_correct: 'false',
         answer_d_correct: 'false',
         answer_e_correct: 'false',
         answer_f_correct: 'false',
      },
      explanation:
         'The correct way to send JSON data via cURL is by using `curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data))`.',
      tip: null,
      tags: [{ name: 'PHP' }],
      category: 'Code',
      difficulty: 'Hard',
   },
   {
      id: 5437,
      question: 'How can you access a Vuex state property inside a component?',
      description: 'Understanding how to use Vuex state inside Vue components.',
      answers: {
         answer_a: "Using 'this.$state'",
         answer_b: "Using 'this.state'",
         answer_c: "Using 'this.$store.state.propertyName'",
         answer_d: "Using 'store.getState()'",
         answer_e: null,
         answer_f: null,
      },
      multiple_correct_answers: 'false',
      correct_answers: {
         answer_a_correct: 'false',
         answer_b_correct: 'false',
         answer_c_correct: 'true',
         answer_d_correct: 'false',
         answer_e_correct: 'false',
         answer_f_correct: 'false',
      },
      explanation:
         "To access a Vuex state property, use 'this.$store.state.propertyName'.",
      tip: null,
      tags: [{ name: 'VueJS' }],
      category: 'VueJS',
      difficulty: 'Medium',
   },
   {
      id: 1153,
      question:
         'If you want to trigger a manual rollout of an updated image for a DeploymentConfig, which command would you use?',
      description: null,
      answers: {
         answer_a: 'oc rollout latest <DeploymentConfig-name>',
         answer_b: 'oc apply rollout <DeploymentConfig-name>',
         answer_c: 'oc rollout start <DeploymentConfig-name>',
         answer_d: 'oc deploy <DeploymentConfig-name>',
         answer_e: null,
         answer_f: null,
      },
      multiple_correct_answers: 'false',
      correct_answers: {
         answer_a_correct: 'true',
         answer_b_correct: 'false',
         answer_c_correct: 'false',
         answer_d_correct: 'false',
         answer_e_correct: 'false',
         answer_f_correct: 'false',
      },
      explanation: null,
      tip: null,
      tags: [{ name: 'Openshift' }],
      category: 'DevOps',
      difficulty: 'Medium',
   },
   {
      id: 5036,
      question:
         "What is the difference between 'crypto.privateEncrypt()' and 'crypto.privateDecrypt()'?",
      description: 'Understanding private key encryption and decryption.',
      answers: {
         answer_a:
            "'privateEncrypt()' encrypts data with a private key, while 'privateDecrypt()' decrypts data encrypted with the same private key",
         answer_b:
            "'privateEncrypt()' encrypts data with a public key, while 'privateDecrypt()' decrypts data with a private key",
         answer_c:
            "'privateEncrypt()' encrypts data with a private key, while 'privateDecrypt()' decrypts data with a public key",
         answer_d:
            "'privateEncrypt()' and 'privateDecrypt()' perform the same operation",
         answer_e: null,
         answer_f: null,
      },
      multiple_correct_answers: 'false',
      correct_answers: {
         answer_a_correct: 'true',
         answer_b_correct: 'false',
         answer_c_correct: 'false',
         answer_d_correct: 'false',
         answer_e_correct: 'false',
         answer_f_correct: 'false',
      },
      explanation:
         "'crypto.privateEncrypt()' encrypts data using a private key, and 'crypto.privateDecrypt()' decrypts data encrypted with that private key.",
      tip: null,
      tags: [{ name: 'nodeJS' }],
      category: 'NodeJs',
      difficulty: 'Hard',
   },
   {
      id: 8837,
      question:
         'Which function allows a script to continue execution after an exception is thrown?',
      description: 'Understanding exception handling flow in PHP.',
      answers: {
         answer_a: 'recover_exception()',
         answer_b: 'try_recover()',
         answer_c: 'catch_exception()',
         answer_d: 'set_exception_handler()',
         answer_e: null,
         answer_f: null,
      },
      multiple_correct_answers: 'false',
      correct_answers: {
         answer_a_correct: 'false',
         answer_b_correct: 'false',
         answer_c_correct: 'false',
         answer_d_correct: 'true',
         answer_e_correct: 'false',
         answer_f_correct: 'false',
      },
      explanation:
         'A custom exception handler set with `set_exception_handler()` allows exceptions to be handled without stopping execution.',
      tip: null,
      tags: [{ name: 'PHP' }],
      category: 'Code',
      difficulty: 'Hard',
   },
   {
      id: 9551,
      question: 'How do you define important text in HTML?',
      description: 'Semantic emphasis.',
      answers: {
         answer_a: '<important>',
         answer_b: '<strong>',
         answer_c: '<bold>',
         answer_d: '<em>',
         answer_e: null,
         answer_f: null,
      },
      multiple_correct_answers: 'false',
      correct_answers: {
         answer_a_correct: 'false',
         answer_b_correct: 'true',
         answer_c_correct: 'false',
         answer_d_correct: 'false',
         answer_e_correct: 'false',
         answer_f_correct: 'false',
      },
      explanation: '<strong> semantically indicates important text.',
      tip: null,
      tags: [{ name: 'HTML' }],
      category: 'HTML',
      difficulty: 'Easy',
   },
   {
      id: 560,
      question:
         'How are functions in PHP which starts with __ (double underscore) known as?',
      description: null,
      answers: {
         answer_a: 'Inbuilt Function',
         answer_b: 'User Defined Function',
         answer_c: 'Magic Function',
         answer_d: 'Default Function',
         answer_e: null,
         answer_f: null,
      },
      multiple_correct_answers: 'false',
      correct_answers: {
         answer_a_correct: 'false',
         answer_b_correct: 'false',
         answer_c_correct: 'true',
         answer_d_correct: 'false',
         answer_e_correct: 'false',
         answer_f_correct: 'false',
      },
      explanation: null,
      tip: null,
      tags: [{ name: 'PHP' }],
      category: 'Code',
      difficulty: 'Medium',
   },
   {
      id: 7537,
      question:
         "What will the following loop do?\n```bash\nwhile true; do echo 'Running...'; sleep 1; done\n```",
      description: 'Understanding infinite loops in Bash.',
      answers: {
         answer_a: "It will print 'Running...' every second indefinitely",
         answer_b: "It will print 'Running...' once",
         answer_c: "It will print 'Running...' 10 times",
         answer_d: 'It will throw an error',
         answer_e: null,
         answer_f: null,
      },
      multiple_correct_answers: 'false',
      correct_answers: {
         answer_a_correct: 'true',
         answer_b_correct: 'false',
         answer_c_correct: 'false',
         answer_d_correct: 'false',
         answer_e_correct: 'false',
         answer_f_correct: 'false',
      },
      explanation:
         "The `while true` loop runs indefinitely, printing 'Running...' every second.",
      tip: null,
      tags: [{ name: 'BASH' }],
      category: 'bash',
      difficulty: 'Easy',
   },
   {
      id: 5090,
      question:
         "What happens if you call 'removeAllListeners()' without any arguments?",
      description: "Using 'removeAllListeners' without arguments.",
      answers: {
         answer_a: 'It removes all listeners for all events',
         answer_b: 'It throws an error',
         answer_c: "It removes listeners only for the 'default' event",
         answer_d: 'It does nothing',
         answer_e: null,
         answer_f: null,
      },
      multiple_correct_answers: 'false',
      correct_answers: {
         answer_a_correct: 'true',
         answer_b_correct: 'false',
         answer_c_correct: 'false',
         answer_d_correct: 'false',
         answer_e_correct: 'false',
         answer_f_correct: 'false',
      },
      explanation:
         "Calling 'removeAllListeners()' without arguments removes all listeners for all events.",
      tip: null,
      tags: [{ name: 'nodeJS' }],
      category: 'NodeJs',
      difficulty: 'Medium',
   },
   {
      id: 9405,
      question:
         'Which HTTP header should be set to correctly send JSON data via an API?',
      description:
         'Understanding the correct HTTP headers for JSON API requests.',
      answers: {
         answer_a: 'Content-Type: application/json',
         answer_b: 'Content-Type: text/json',
         answer_c: 'Content-Type: multipart/form-data',
         answer_d: 'Content-Type: text/plain',
         answer_e: null,
         answer_f: null,
      },
      multiple_correct_answers: 'false',
      correct_answers: {
         answer_a_correct: 'true',
         answer_b_correct: 'false',
         answer_c_correct: 'false',
         answer_d_correct: 'false',
         answer_e_correct: 'false',
         answer_f_correct: 'false',
      },
      explanation:
         'The correct header for sending JSON data is `Content-Type: application/json`.',
      tip: null,
      tags: [{ name: 'PHP' }],
      category: 'Code',
      difficulty: 'Hard',
   },
   {
      id: 10405,
      question:
         'You are troubleshooting network connectivity issues on a Linux server. Which command can help you view the routing table?',
      description: 'Examining the routing table for network troubleshooting.',
      answers: {
         answer_a: 'route',
         answer_b: 'netstat -r',
         answer_c: 'ip route show',
         answer_d: 'traceroute',
         answer_e: null,
         answer_f: null,
      },
      multiple_correct_answers: 'false',
      correct_answers: {
         answer_a_correct: 'false',
         answer_b_correct: 'true',
         answer_c_correct: 'false',
         answer_d_correct: 'false',
         answer_e_correct: 'false',
         answer_f_correct: 'false',
      },
      explanation:
         "The 'netstat -r' command displays the routing table, which is essential for diagnosing network connectivity problems.",
      tip: 'Regularly check the routing table to ensure proper network routing and troubleshoot connectivity issues effectively.',
      tags: [{ name: 'Linux' }],
      category: 'Linux',
      difficulty: 'Easy',
   },
   {
      id: 701,
      question:
         'How can you count for a particular pattern occurrences in a file?',
      description: null,
      answers: {
         answer_a: 'grep −c “pattern” <file>',
         answer_b: 'grep −k “pattern” <file>',
         answer_c: 'cat <file> | wc -k “pattern”',
         answer_d: 'cat <file> | wc -l “pattern”',
         answer_e: null,
         answer_f: null,
      },
      multiple_correct_answers: 'false',
      correct_answers: {
         answer_a_correct: 'true',
         answer_b_correct: 'false',
         answer_c_correct: 'false',
         answer_d_correct: 'false',
         answer_e_correct: 'false',
         answer_f_correct: 'false',
      },
      explanation: null,
      tip: null,
      tags: [{ name: 'BASH' }],
      category: 'Linux',
      difficulty: 'Medium',
   },
   {
      id: 4095,
      question:
         "Which WordPress function is used to retrieve the current user's ID?",
      description: 'Working with user data in WordPress.',
      answers: {
         answer_a: 'get_user_id()',
         answer_b: 'wp_get_current_user()',
         answer_c: 'current_user_id()',
         answer_d: 'get_current_user()',
         answer_e: null,
         answer_f: null,
      },
      multiple_correct_answers: 'false',
      correct_answers: {
         answer_a_correct: 'false',
         answer_b_correct: 'true',
         answer_c_correct: 'false',
         answer_d_correct: 'false',
         answer_e_correct: 'false',
         answer_f_correct: 'false',
      },
      explanation:
         "`wp_get_current_user()` retrieves the current logged-in user's data, including the user ID.",
      tip: null,
      tags: [{ name: 'WordPress' }],
      category: 'WordPress',
      difficulty: 'Hard',
   },
   {
      id: 8066,
      question:
         'Which command is used to check the connection to a server on a specific port?',
      description: 'Understanding how to check network connections in Bash.',
      answers: {
         answer_a: 'nc',
         answer_b: 'ping',
         answer_c: 'wget',
         answer_d: 'telnet',
         answer_e: null,
         answer_f: null,
      },
      multiple_correct_answers: 'false',
      correct_answers: {
         answer_a_correct: 'true',
         answer_b_correct: 'false',
         answer_c_correct: 'false',
         answer_d_correct: 'false',
         answer_e_correct: 'false',
         answer_f_correct: 'false',
      },
      explanation:
         '`nc` (Netcat) is used to check connections to a specific port on a server.',
      tip: null,
      tags: [{ name: 'BASH' }],
      category: 'bash',
      difficulty: 'Easy',
   },
   {
      id: 5157,
      question: 'What is the role of `global.gc()` in Node.js?',
      description: 'Using `global.gc()`.',
      answers: {
         answer_a:
            'It triggers garbage collection manually when the `--expose-gc` flag is enabled',
         answer_b: 'It disables automatic garbage collection',
         answer_c: 'It optimizes memory allocation',
         answer_d: 'It logs garbage collection events',
         answer_e: null,
         answer_f: null,
      },
      multiple_correct_answers: 'false',
      correct_answers: {
         answer_a_correct: 'true',
         answer_b_correct: 'false',
         answer_c_correct: 'false',
         answer_d_correct: 'false',
         answer_e_correct: 'false',
         answer_f_correct: 'false',
      },
      explanation:
         '`global.gc()` triggers garbage collection manually, but only when the `--expose-gc` flag is enabled.',
      tip: null,
      tags: [{ name: 'nodeJS' }],
      category: 'NodeJs',
      difficulty: 'Medium',
   },
];
